

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : B2BFC85B09FB1A4F78433F84A4D4FF08977F494FAA1F88CE9D11D9859AC377C2
; Input MD5    : 0DA2F4490479D4D6E80993AD90E289CB
; Input CRC32  : DD284E4E

; File Name   : /home/xzh/linux/asm/assembly.bin
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 0200h Loaded length: 0200h

                .8086
                .model flat

; ===========================================================================

; Segment type: Pure code
seg000          segment byte public 'CODE'
                assume cs:seg000
                assume es:nothing, ss:nothing, ds:nothing
                db 0B8h
                align 2
                db 0B8h
                db 8Eh, 0D8h, 0C6h, 6, 2 dup(0), 41h, 0C6h, 6, 1, 0, 4
                db 0C6h, 6, 2, 0, 73h, 0C6h, 6, 3, 0, 14h, 0C6h, 6, 4
                db 0, 73h, 0C6h, 6, 5, 0, 24h, 0C6h, 2 dup(6), 0, 65h
                db 0C6h, 6, 7, 0, 34h, 0C6h, 6, 8, 0, 6Dh, 0C6h, 6, 9
                db 0, 44h, 0C6h, 6, 0Ah, 0, 62h, 0C6h, 6, 0Bh, 0, 54h
                db 0C6h, 6, 0Ch, 0, 6Ch, 0C6h, 6, 0Dh, 0, 64h, 0C6h, 6
                db 0Eh, 0, 79h, 0C6h, 6, 1Fh, 0, 74h, 0C6h, 6, 10h, 0
                db 2Eh, 0C6h, 6, 11h, 0, 84h, 19Fh dup(0), 55h, 0AAh
seg000          ends


                end
